neusta_converter:
  converter:
    pimcore.areabrick.config.brick.converter:
      target: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Model\Brick
      populators:
        - pimcore.areabrick.config.brick.page.populator
      properties:
        name: ~
        id: ~
        version: ~
        description: ~
        template: ~

    pimcore.areabrick.config.page.converter:
      target: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Model\Page
      properties:
        published: ~
        url: fullPath
