neusta_converter:
  converter:
    brick.converter:
      target: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Model\BrickView
      populators:
        - Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPagePopulator
      properties:
        name: ~
        id: ~
        tags: ~
