services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $revealJsPublicPath: '/bundles/neustapimcorepresentation/reveal.js-master'

    Neusta\Pimcore\EditorConfigBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Neusta\Pimcore\EditorConfigBundle\Renderer\SimplePresentationRenderer: ~
    Neusta\Pimcore\EditorConfigBundle\Renderer\PresentationRenderer:
        alias: Neusta\Pimcore\EditorConfigBundle\Renderer\SimplePresentationRenderer
    Neusta\Pimcore\EditorConfigBundle\Renderer\SimpleSlideRenderer: ~
    Neusta\Pimcore\EditorConfigBundle\Renderer\SlideRenderer:
        alias: Neusta\Pimcore\EditorConfigBundle\Renderer\SimpleSlideRenderer
    Neusta\Pimcore\EditorConfigBundle\Twig\PresentationExtension: ~
