imports:
  - { resource: packages/* }
  - { resource: pimcore/* }

services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

    Neusta\Pimcore\AreabrickConfigBundle\Controller\Admin\AreabrickOverviewController:
      public: true
      arguments:
        $brickConverter: '@pimcore.areabrick.config.brick.converter'
      tags: [ 'controller.service_arguments' ]

    Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPagePopulator: ~

