imports:
  - { resource: packages/* }
  - { resource: pimcore/* }

services:
  _defaults:
    autowire: true
    autoconfigure: true

    Neusta\Pimcore\AreabrickConfigBundle\Controller\Admin\AreabrickOverviewController:
      public: true
      arguments:
        $brickConverter: '@pimcore.areabrick.config.brick.converter'
      tags: [ 'controller.service_arguments' ]

    Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPagePopulator: ~

