services:
  _defaults:
    autowire: true
    autoconfigure: true

  Neusta\Pimcore\AreabrickConfigBundle\Controller\Admin\AreabrickOverviewController:
    public: true
    arguments:
      $brickConverter: '@pimcore.areabrick.config.brick.converter'
    tags: [ 'controller.service_arguments' ]

  pimcore.areabrick.config.brick.page.populator:
    class: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPagePopulator
    arguments:
      $pageConverter: '@pimcore.areabrick.config.page.converter'

  Neusta\Pimcore\AreabrickConfigBundle\EventListener\PimcoreAdminListener:
    tags:
      - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.css, method: addCSSFiles }
      - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addJSFiles }
