neusta_converter:
  converter:
    pimcore_areabrick_config.brick.converter:
      target: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Model\Brick
      populators:
        - Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPagePopulator
      properties:
        id: ~
        name: ~
        version: ~
        description: ~
        template: ~

    pimcore_areabrick_config.page.converter:
      target: Neusta\Pimcore\AreabrickConfigBundle\Bricks\Model\Page
      populators:
        - Neusta\Pimcore\AreabrickConfigBundle\Bricks\Populator\BrickPageEditModeUrlPopulator
      properties:
        published: ~
        url: fullPath
